# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
---
# handlers file for wyebot.wifi.prometheus_exporter

- name: Restart wyebot prometheus exporter
  ansible.builtin.command:
    cmd: docker restart {{ wyebot_prometheus_container_name }}
  changed_when: true
