# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
---
galaxy_info:
  author: Steve Fulmer
  description: Deploy a Wyebot Prometheus exporter container for WiFi metrics collection
  company: Wyebot

  license: GPL-3.0-or-later

  min_ansible_version: "2.16"

  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - focal
        - jammy

  galaxy_tags:
    - wyebot
    - prometheus
    - monitoring
    - docker
    - wifi

dependencies: []
